FROM ubuntu:16.04

# Need to be able to use add-apt-repository and must run update before
# it'll work
RUN apt-get update
RUN apt-get -y install software-properties-common curl

# Add NGINX Repo
RUN add-apt-repository ppa:nginx/development
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -

# Install Dependencies
RUN apt-get -y install git nodejs nginx php5 php5-fpm php5-mysql php-apc php5-imagick php5-curl pngcrush build-essential gettext nano

# Prevent PHP version being shared via headers
RUN sed -i -e "s/expose_php = On/expose_php = Off/g" /etc/php5/fpm/php.ini

# Remove the default Nginx configuration file
RUN rm /etc/nginx/sites-enabled/default

ADD src/docker/nginx/gauntface-shared.conf /etc/nginx/gauntface-shared.conf
ADD src/docker/nginx/fastcgi-params.tmpl /etc/nginx/fastcgi-params.tmpl
ADD src/docker/startup.sh /home/gauntface/docker/startup.sh

CMD ["/home/gauntface/docker/startup.sh"]
